implement p-to-bf
easystats/bayestestR pull request #529
Opened 2022-05-16 08:02 UTC by strengejacke

``` r
data(iris)
model <- lm(Petal.Length ~ Sepal.Length + Species, data = iris)
bayestestR::p_to_bf(model)
#>           Parameter            p           BF
#> 1       (Intercept) 1.005180e-11 3.693268e-10
#> 2      Sepal.Length 1.121002e-28 4.118823e-27
#> 3 Speciesversicolor 9.645641e-67 3.544035e-65
#> 4  Speciesvirginica 4.917626e-71 1.806851e-69
```

<sup>Created on 2022-05-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2022-05-17 10:48 UTC, mattansb commented
Fixed: Now returns BF10 (instead of BF01, which is what the formula in the paper give...)

This paper is essentially trying to approximate the BIC to BF approximation (relaying on how Wald tests are asymptotically LRTs)... 

Here is a demo (using @bwiernik `pipebind`!)

``` r
library(bayestestR)
library(pipebind)
#> Warning: package 'pipebind' was built under R version 4.1.3

m0 <- lm(mpg ~ 1, mtcars)
m1 <- lm(mpg ~ am, mtcars)
m2 <- lm(mpg ~ factor(cyl), mtcars)

bic_to_bf(BIC(m1), denominator = BIC(m0))
#> [1] 222.005
m1 |> 
  parameters::p_value() |> 
  bind(x, x[2, "p"]) |> 
  p_to_bf(n_obs = nrow(mtcars))
#>              p       BF
#> 1 0.0002850207 206.7413

bic_to_bf(BIC(m2), denominator = BIC(m0))
#> [1] 45355714
anova(m2) |> 
  parameters::p_value() |> 
  bind(x, x[1, "p"]) |> 
  p_to_bf(n_obs = nrow(mtcars))
#>              p       BF
#> 1 4.978919e-09 11835011
```

<sup>Created on 2022-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2022-05-17 10:51 UTC, mattansb commented
If we do decide to merge this PR, I hope we don't endorse this down the line by adding these to any outputs.

2022-05-17 10:53 UTC, DominiqueMakowski commented
> If we do decide to merge this PR, I hope we don't endorse this down the line by adding these to any outputs.

yes i agree

2022-05-17 11:01 UTC, bwiernik requested changes
Some suggestions for naming and documentation to provide context and recommended usage

2022-05-17 11:01 UTC, bwiernik commented on R/p_to_bf.R
> +#' @seealso [bic_to_bf()]
```suggestion
#' @seealso [bic_to_bf()] for more accurate approximate Bayes factors.
```

2022-05-17 11:06 UTC, DominiqueMakowski commented
tbh i wouldn't call it "pseudo" it's a bit long as a name and you know... what is "pseudo" really, if all approximations are pseudo then we should pseudo a *lot* of stuff ^^

2022-05-17 11:16 UTC, bwiernik commented
My thinking is that this is much more of a heuristic approximation than other approximations. And it’s a bit long for a reason 😜

2022-05-17 11:23 UTC, mattansb commented
If you read the paper they are using the p-value to approximate the SE to approximate the LRT to approximate for the BIC comparisons that can be used to produce BFs. That is a long chain, with many assumptions...

I think `p_to_pseudo_bf()` is a good compromise...

2022-05-17 11:29 UTC, DominiqueMakowski commented
okay i'm convinced

2022-09-10 07:26 UTC, DominiqueMakowski commented
we should have merged this while i was onboard with p_to_pseudo_bf, now after looking back I think p_to_bf and put the dicslaimer in the title + docstrings should be enough. I mean people will *at least* check the title of the function ^^ wadayathink?

2022-09-10 11:03 UTC, mattansb commented
I mean....... No...

![Screenshot_20220910-140229.png](https://user-images.githubusercontent.com/35330040/189480361-5123abe8-8c8d-4675-b722-46292fd41b07.png)

2022-09-10 11:06 UTC, strengejacke commented
BF is pseudo, anyway, so `p_to_bf()` includes all necessary information?

2022-09-10 11:34 UTC, bwiernik approved these changes

2022-09-13 10:22 UTC, strengejacke commented
I'm open for both suggestion, i.e. renaming to `p_to_pseudo_bf()`, or keep it as it is. @DominiqueMakowski do you plan to merge this before submitting _bayestestR_? I think it's feature complete now.

2022-09-13 11:00 UTC, mattansb commented
I vote pseudo 👏

2022-09-13 11:48 UTC, DominiqueMakowski commented
I vote for keeping it as is

2022-09-13 12:48 UTC, strengejacke commented
![image](https://user-images.githubusercontent.com/26301769/189905157-001ea8a6-3012-4b4f-831e-709456e34385.png)

2022-09-13 12:50 UTC, strengejacke commented
@easystats/core-team we need some help here...

2022-09-13 13:22 UTC, bwiernik commented
Compromise, leave the name and change the output to say “pseudo-BF”?

2022-09-13 13:35 UTC, strengejacke commented
> Compromise, leave the name and change the output to say “pseudo-BF”?

Yeah, that's what I already did in the print method, as table header :-)

2022-09-13 13:36 UTC, strengejacke commented
![image](https://user-images.githubusercontent.com/26301769/189915635-b8da5ba5-e046-4459-b478-acb76e80d3cd.png)

2022-09-13 13:42 UTC, DominiqueMakowski commented
> Yeah, that's what I already did

Meme lord + forward thinker nice

2022-09-13 13:43 UTC, DominiqueMakowski commented
Now let's hope this humble offering pleases @mattansb 🙏

2022-09-13 14:03 UTC, bwiernik commented
I'm good with it, so we have a majority 😜

2022-09-13 14:31 UTC, mattansb commented
I'll take it

2022-09-13 14:33 UTC, merged