Fix Redundant Computation of Marginal Likelihood for brmsfit Objects
easystats/bayestestR pull request #573
Opened 2022-10-22 00:27 UTC by ajnafa

# Description

This PR adds a helper function to `bayesfactor_models.R` to check if `brmsfit` objects passed to `bayesfactor_*` functions already include a `marglik` element in the model object and avoids redundant calls to `bridgesampling::bridge_sampler` if the criteria already exists since this can be computationally expensive.

# Proposed Changes

- [x]  Add a helper function `.get_brmsfit_mML` to `bayesfactor_models.R`
- [x]  Modify `.bayesfactor_models_stan_REG` to check for `marglik` in `brmsfit` objects before calling `bridgesampling::bridge_sampler`
- [x]  Run unit tests to verify the changes didn't break anything else in the package

2022-10-22 14:47 UTC, strengejacke requested changes

2022-10-22 14:47 UTC, strengejacke commented on R/bayesfactor_models.R
> +#' @importFrom stats median
Please don't use `importFrom`, rather use `stats::median` directly below.

2022-10-22 14:47 UTC, strengejacke commented on R/bayesfactor_models.R
> +  if (all(grepl("brmsfit", check_brmsfit))) {
I suggest using`all(check_brmsfit == "brmsfit")`, which is faster:

``` r
check_brmsfit <- c("a", "b", "brmsfit", "c", "brmsfit")
microbenchmark::microbenchmark(
  all(grepl("brmsfit", check_brmsfit)),
  all(grepl("brmsfit", check_brmsfit, fixed = TRUE)),
  all(check_brmsfit == "brmsfit"),
  times = 1000
)
#> Unit: nanoseconds
#>                                                expr  min   lq   mean median
#>                all(grepl("brmsfit", check_brmsfit)) 5600 5800 6479.5   5900
#>  all(grepl("brmsfit", check_brmsfit, fixed = TRUE)) 1700 1900 2122.8   2000
#>                     all(check_brmsfit == "brmsfit")  300  400  440.6    400
```

2022-10-23 05:27 UTC, mattansb commented
@ajnafa LGTM

Can you add a unit test for this?

2022-10-23 05:38 UTC, ajnafa commented
> @ajnafa LGTM
> 
> Can you add a unit test for this?

Yeah, I can add one to the test-bayesfactor_models.R file when I get into the office tomorrow.

2022-10-23 05:52 UTC, mattansb commented
Awesome thanks!
(Sorry to interrupt your weekend - weekends here are Fri-Sat)

2022-10-26 17:46 UTC, ajnafa commented
Wanted to follow up on this regarding unit tests because when I try to add the marginal likelihood to the brmsfit objects from within the package's project it crashes my R session. I'm currently trying to diagnose the issue but that is mostly the reason I haven't finished these yet.

2022-10-30 14:21 UTC, mattansb commented
I just want to add another test of my own and then we can merge (:

2022-10-31 06:49 UTC, mattansb commented
Looks good - should we address this in `NEWS`?

2022-11-29 19:20 UTC, strengejacke commented
Isn't this PR ready to merge?

2022-11-30 02:13 UTC, bwiernik commented
Looks okay ti me

2022-11-30 06:51 UTC, merged

2022-11-30 06:51 UTC, strengejacke commented
Thanks, @ajnafa !